cols = ['ID', 'Date submitted',
        'Please enter your age..',
        'Please select your gender...',
        'Rate how well You know the other subject prior to the negotiation. (1 - Unknown , 5 - Very well known)',
        'I see myself as someone who... [Worries a lot]',
        'I see myself as someone who... [Gets nervous easily]',
        'I see myself as someone who... [Remains calm in tense situations]',
        'I see myself as someone who... [Is talkative]',
        'I see myself as someone who... [Is outgoing, sociable]',
        'I see myself as someone who... [Is reserved]',
        'I see myself as someone who... [Is original, comes up with new ideas]',
        'I see myself as someone who... [Values artistic, aesthetic experiences]',
        'I see myself as someone who... [Has an active imagination]',
        'I see myself as someone who... [Is sometimes rude to others]',
        'I see myself as someone who... [Has a forgiving nature]',
        'I see myself as someone who... [Is considerate and kind to almost everyone]',
        'I see myself as someone who... [Does a thorough job]',
        'I see myself as someone who... [Tends to be lazy]',
        'I see myself as someone who... [Does things efficiently]',
        "Please fill in the settlement amount which would result in the following levels of satisfaction for you (note: marginally satisfactory must equal the bottom line you've been given in your Confidential Instructions) [Marginally satisfactory]",
        "Please fill in the settlement amount which would result in the following levels of satisfaction for you (note: marginally satisfactory must equal the bottom line you've been given in your Confidential Instructions) [Satisfactory]",
        "Please fill in the settlement amount which would result in the following levels of satisfaction for you (note: marginally satisfactory must equal the bottom line you've been given in your Confidential Instructions) [Very satisfactory]",
        "Please fill in the settlement amount which would result in the following levels of satisfaction for you (note: marginally satisfactory must equal the bottom line you've been given in your Confidential Instructions) [Optimal]",
        'Is there any amount which, though seemingly even better for you than the OPTIMAL figure you just listed, you would reject as being unfair to the other side?',
        'Please rate each item on the scale. Consider how you are feeling right now. [General discomfort]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Fatigue]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Headache]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Eye strain]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Difficulty focusing]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Increased salivation]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Sweating]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Nausea]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Difficulty concentrating]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Fullness of head]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Blurred vision]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Dizzy (eyes open)]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Dizzy (eyes closed)]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Vertigo]',
        'Please rate each item on the scale. Consider how you are feeling right now. [Stomach awareness]',
        'Please rate each item on the scale. Consider how you are feeling right now. [BurpingPost-Negotiation]',
        'Please rate each item on the scale. Consider how you are feeling right now. [General discomfort].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Fatigue].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Headache].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Eye strain].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Difficulty focusing].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Increased salivation].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Sweating].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Nausea].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Difficulty concentrating].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Fullness of head].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Blurred vision].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Dizzy (eyes open)].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Dizzy (eyes closed)].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Vertigo].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [Stomach awareness].1',
        'Please rate each item on the scale. Consider how you are feeling right now. [BurpingPost-Negotiation].1',
        'Did you reach an agreement?',
        'For what amount?',
        'How would you now describe the outcome?',
        'Did your standards for satisfaction…',
        "Why couldn't you reach an agreement?",
        'Please select the picture below which best describes your realtionship with your interaction partner.',
        'Please select the answer that best describes your experience during the negotiation. [I think the interaction with my negotiation partner was smooth.]',
        'Please select the answer that best describes your experience during the negotiation. [I think the interaction with my negotiation partner was awkward.]',
        'Please select the answer that best describes your experience during the negotiation. [I think my negotiation partner is very likeable.]',
        'Please select the answer that best describes your experience during the negotiation. [I think my negotiation partner is very engaging.]',
        'Please select the answer that best describes your experience during the negotiation. [I think my negotiation partner is very kind.]',
        'Please select the answer that best describes your experience during the negotiation. [I think my negotiation partner is very unfriendly.]',
        'Please select the answer that best describes your experience during the negotiation. [I think my negotiation partner is very unpleasant.]',
        'Please select the answer that best describes your experience during the negotiation. [I think my negotiation partner is very trustworthy.]',
        'Please select the answer that best describes your experience during the negotiation. [I think my negotiation partner is very honest.]',
        'Please select the answer that best describes your experience during the negotiation. [I think my negotiation partner is very responsible.]',
        'Please select the answer that best describes your experience during the negotiation. [I think my negotiation partner is very unreliable.]',
        'Please select the answer that best describes your experience during the negotiation. [I think my negotiation partner is very insincere.]',
        'Please select the answer that best describes your experience during the negotiation. [I think my negotiation partner is very similar to me.]',
        'Please select the answer that best describes your experience during the negotiation. [I think my negotiation partner is very different from me.]',
        'I see my negotiation partner as someone who... [Worries a lot]',
        'I see my negotiation partner as someone who... [Gets nervous easily]',
        'I see my negotiation partner as someone who... [Remains calm in tense situations]',
        'I see my negotiation partner as someone who... [Is talkative]',
        'I see my negotiation partner as someone who... [Is outgoing, sociable]',
        'I see my negotiation partner as someone who... [Is reserved]',
        'I see my negotiation partner as someone who... [Is original, comes up with new ideas]',
        'I see my negotiation partner as someone who... [Values artistic, aesthetic experiences]',
        'I see my negotiation partner as someone who... [Has an active imagination]',
        'I see my negotiation partner as someone who... [Is sometimes rude to others]',
        'I see my negotiation partner as someone who... [Has a forgiving nature]',
        'I see my negotiation partner as someone who... [Is considerate and kind to almost everyone]',
        'I see my negotiation partner as someone who... [Does a thorough job]',
        'I see my negotiation partner as someone who... [Tends to be lazy]',
        'I see my negotiation partner as someone who... [Does things efficiently]']
